# Generated by Django 5.0.2 on 2025-10-14 12:19

from django.db import migrations

def populate_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('accounts', 'Role')
    for role_name in User.objects.values_list('role', flat=True).distinct():
        if role_name:
            Role.objects.get_or_create(name=role_name)

    for user in User.objects.all():
        if user.role:
            user.role_fk = Role.objects.get(name=user.role)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_user_gender_user_last_login_at_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]