# Generated by Django 5.0.2 on 2025-10-23 09:33

from django.db import migrations


def populate_default_settings(apps, schema_editor):
    """Populate default application settings"""
    ApplicationSetting = apps.get_model('accounts', 'ApplicationSetting')

    default_settings = [
        {
            'setting_key': 'application_name',
            'setting_value': 'TMS Application',
            'setting_type': 'string',
            'description': 'The name of the application displayed throughout the system',
            'is_public': True
        },
        {
            'setting_key': 'maintenance_mode',
            'setting_value': 'false',
            'setting_type': 'boolean',
            'description': 'Enable maintenance mode to prevent user access',
            'is_public': True
        },
        {
            'setting_key': 'support_email',
            'setting_value': 'support@example.com',
            'setting_type': 'string',
            'description': 'Support email address for user inquiries',
            'is_public': True
        },
        {
            'setting_key': 'default_currency',
            'setting_value': 'USD',
            'setting_type': 'string',
            'description': 'Default currency code for financial transactions',
            'is_public': True
        },
        {
            'setting_key': 'enable_email_notifications',
            'setting_value': 'true',
            'setting_type': 'boolean',
            'description': 'Enable or disable system-wide email notifications',
            'is_public': False
        },
        {
            'setting_key': 'session_timeout_minutes',
            'setting_value': '480',
            'setting_type': 'number',
            'description': 'User session timeout in minutes (default: 8 hours)',
            'is_public': False
        },
        {
            'setting_key': 'max_file_upload_size',
            'setting_value': '10485760',
            'setting_type': 'number',
            'description': 'Maximum file upload size in bytes (default: 10MB)',
            'is_public': False
        }
    ]

    for setting_data in default_settings:
        ApplicationSetting.objects.get_or_create(
            setting_key=setting_data['setting_key'],
            defaults={
                'setting_value': setting_data['setting_value'],
                'setting_type': setting_data['setting_type'],
                'description': setting_data['description'],
                'is_public': setting_data['is_public']
            }
        )


def remove_default_settings(apps, schema_editor):
    """Remove default settings on migration reversal"""
    ApplicationSetting = apps.get_model('accounts', 'ApplicationSetting')

    default_setting_keys = [
        'application_name',
        'maintenance_mode',
        'support_email',
        'default_currency',
        'enable_email_notifications',
        'session_timeout_minutes',
        'max_file_upload_size'
    ]

    ApplicationSetting.objects.filter(setting_key__in=default_setting_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_applicationsetting'),
    ]

    operations = [
        migrations.RunPython(populate_default_settings, remove_default_settings),
    ]
