# Generated by Django 5.0.2 on 2025-11-09 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approval_override', 'Approval Workflow Override'), ('permission_override', 'Permission Override'), ('data_modification', 'Direct Data Modification'), ('settings_change', 'Settings Change'), ('user_modification', 'User Account Modification'), ('other', 'Other Administrative Action')], max_length=50)),
                ('entity_type', models.CharField(help_text='Type of entity affected (e.g., TransportRequest, TravelRequest)', max_length=255)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=255)),
                ('description', models.TextField(help_text='Description of the action taken')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ad_created_b36f06_idx'), models.Index(fields=['admin', '-created_at'], name='accounts_ad_admin_i_0fdb00_idx'), models.Index(fields=['action_type', '-created_at'], name='accounts_ad_action__977862_idx')],
            },
        ),
    ]
