# Generated by Django 5.2.8 on 2025-12-24 05:24

from django.db import migrations


def remove_email_settings(apps, schema_editor):
    """
    Remove email-related settings from ApplicationSetting.
    Email configuration is now managed exclusively via environment variables (.env file).
    """
    ApplicationSetting = apps.get_model('accounts', 'ApplicationSetting')

    # List of email settings to remove
    email_setting_keys = [
        'smtp_host',
        'smtp_port',
        'smtp_use_tls',
        'smtp_use_ssl',
        'smtp_username',
        'smtp_password',
        'default_from_email',
        'server_email',
        'email_admin',
        'brevo_api_key'
    ]

    deleted_count = ApplicationSetting.objects.filter(setting_key__in=email_setting_keys).delete()[0]
    print(f"Removed {deleted_count} email settings from database (now using .env file)")


def restore_email_settings(apps, schema_editor):
    """
    Reverse migration - restore email settings to database.
    Note: Values will need to be reconfigured manually.
    """
    ApplicationSetting = apps.get_model('accounts', 'ApplicationSetting')

    # Only restore the structure, not the actual values
    # Users will need to reconfigure these in the admin panel
    print("Reverse migration: Email settings structure can be restored, but values must be reconfigured manually")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_refactor_permissions'),
    ]

    operations = [
        migrations.RunPython(remove_email_settings, restore_email_settings),
    ]
