# Generated by Django 5.2.8 on 2026-01-11 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_password_reset_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveIndex(
            model_name='adminactionlog',
            name='accounts_ad_admin_i_0fdb00_idx',
        ),
        migrations.RemoveField(
            model_name='adminactionlog',
            name='admin',
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_created', 'User Account Created'), ('user_deleted', 'User Account Deleted'), ('user_deactivated', 'User Account Deactivated'), ('user_activated', 'User Account Activated'), ('user_role_changed', 'User Role Changed'), ('user_permissions_changed', 'User Permissions Changed'), ('password_reset_admin', 'Password Reset by Admin'), ('password_change_forced', 'Forced Password Change'), ('password_changed', 'Password Changed'), ('login_success', 'Successful Login'), ('login_failed', 'Failed Login Attempt'), ('logout', 'User Logout'), ('role_created', 'Role Created'), ('role_deleted', 'Role Deleted'), ('role_permissions_modified', 'Role Permissions Modified'), ('settings_change', 'Application Settings Changed'), ('approval_override', 'Approval Workflow Override'), ('permission_override', 'Permission Override'), ('data_modification', 'Direct Data Modification'), ('other', 'Other Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='entity_id',
            field=models.CharField(blank=True, help_text='ID of the affected entity', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='entity_type',
            field=models.CharField(blank=True, help_text='Type of entity affected (e.g., User, Role, Permission)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ad_user_id_b10aba_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='accounts_ad_entity__6e65a7_idx'),
        ),
    ]
