# Generated by Django 5.0.2 on 2026-02-17 08:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def create_departments_from_existing(apps, schema_editor):
    """
    Create Department records from existing unique department values in User table,
    then link users to their departments.
    """
    User = apps.get_model('accounts', 'User')
    Department = apps.get_model('accounts', 'Department')

    # Get unique department names from old CharField
    unique_departments = User.objects.exclude(
        department_old__isnull=True
    ).exclude(
        department_old=''
    ).values_list('department_old', flat=True).distinct()

    # Create Department records
    dept_map = {}
    for dept_name in unique_departments:
        if dept_name:
            dept, created = Department.objects.get_or_create(
                name=dept_name,
                defaults={
                    'code': dept_name[:50].upper().replace(' ', '_'),
                    'is_active': True
                }
            )
            dept_map[dept_name] = dept

    # Update users to link to new Department FK
    for user in User.objects.exclude(department_old__isnull=True).exclude(department_old=''):
        if user.department_old in dept_map:
            user.department = dept_map[user.department_old]
            user.save(update_fields=['department'])

    print(f"Created {len(dept_map)} departments and migrated user assignments")


def reverse_migration(apps, schema_editor):
    """
    Reverse: Copy department name back to CharField
    """
    User = apps.get_model('accounts', 'User')

    for user in User.objects.filter(department__isnull=False):
        user.department_old = user.department.name
        user.save(update_fields=['department_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_adminactionlog_options_and_more'),
    ]

    operations = [
        # Step 1: Rename old department CharField to department_old
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_old',
        ),

        # Step 2: Create Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code for the department (e.g., IT, HR)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),

        # Step 3: Add new department FK field
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department'),
        ),

        # Step 4: Run data migration
        migrations.RunPython(create_departments_from_existing, reverse_migration),

        # Step 5: Remove old department CharField
        migrations.RemoveField(
            model_name='user',
            name='department_old',
        ),
    ]
