# Generated by Django 5.0.2 on 2026-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_add_combined_request_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, help_text="Job title / position", max_length=255, null=True
            ),
        ),
    ]
