# Generated by Django 5.2.16 on 2026-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_audit_log_user_fk_do_nothing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("user_created", "User Account Created"),
                    ("user_deleted", "User Account Deleted"),
                    ("user_deactivated", "User Account Deactivated"),
                    ("user_activated", "User Account Activated"),
                    ("user_role_changed", "User Role Changed"),
                    ("user_permissions_changed", "User Permissions Changed"),
                    ("password_reset_admin", "Password Reset by Admin"),
                    ("password_change_forced", "Forced Password Change"),
                    ("password_changed", "Password Changed"),
                    ("login_success", "Successful Login"),
                    ("login_failed", "Failed Login Attempt"),
                    ("logout", "User Logout"),
                    ("role_created", "Role Created"),
                    ("role_deleted", "Role Deleted"),
                    ("role_permissions_modified", "Role Permissions Modified"),
                    ("settings_change", "Application Settings Changed"),
                    ("approval_override", "Approval Workflow Override"),
                    ("permission_override", "Permission Override"),
                    ("data_modification", "Direct Data Modification"),
                    ("mfa_enabled", "MFA Enabled"),
                    ("mfa_disabled", "MFA Disabled"),
                    ("mfa_failed", "MFA Verification Failed"),
                    ("privacy_consent_given", "Privacy Consent Given"),
                    ("access_review", "Access Review Completed"),
                    ("password_expired", "Password Expired — Change Forced"),
                    ("workflow_step_approved", "Workflow Step Approved"),
                    ("workflow_step_rejected", "Workflow Step Rejected"),
                    ("workflow_bulk_approve", "Bulk Workflow Approval"),
                    ("workflow_bulk_reject", "Bulk Workflow Rejection"),
                    ("other", "Other Action"),
                ],
                max_length=50,
            ),
        ),
    ]
