# Generated by Django 5.0.2 on 2026-08-11 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_add_meal_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('csv_content', models.TextField(help_text='Raw decoded CSV text to process in the background.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('result_detail', models.JSONField(default=dict, help_text='Full result lists: {created, skipped, errors, unmatched_departments}')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Import Job',
                'verbose_name_plural': 'Bulk Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
