# Generated by Django 5.0.2 on 2025-10-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('trf', '0002_travelrequest_remove_travelrequestform_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='trf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='trf.travelrequest'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='trf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='trf.travelrequest'),
        ),
    ]
