# Generated by Django 5.0.2 on 2025-10-14 19:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_flightbooking_trf_alter_hotelbooking_trf'),
        ('trf', '0003_delete_travelrequestform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cost',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airline_code',
            field=models.CharField(blank=True, help_text='2-letter IATA code (e.g., EK, QR)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='arrival_airport_code',
            field=models.CharField(blank=True, help_text='3-letter IATA code (e.g., LHR)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='arrival_terminal',
            field=models.CharField(blank=True, help_text='Arrival terminal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='baggage_allowance',
            field=models.CharField(blank=True, help_text='Baggage allowance (e.g., 2x23kg)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Travel desk who made the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was created', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='carry_on_allowance',
            field=models.CharField(blank=True, help_text='Carry-on allowance (e.g., 7kg)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='departure_airport_code',
            field=models.CharField(blank=True, help_text='3-letter IATA code (e.g., DXB)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='departure_terminal',
            field=models.CharField(blank=True, help_text='Departure terminal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip'), ('MULTI_CITY', 'Multi City')], default='ONE_WAY', help_text='Type of flight booking', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='meal_preference',
            field=models.CharField(blank=True, help_text='Meal preference code (e.g., VGML, HNML)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Assigned seat number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Special assistance or requests', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='E-ticket number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticketing_date',
            field=models.DateTimeField(blank=True, help_text='Date ticket was issued', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='address',
            field=models.TextField(blank=True, help_text='Full hotel address', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='airport_transfer',
            field=models.BooleanField(default=False, help_text='Airport transfer included'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='bed_preference',
            field=models.CharField(blank=True, help_text='Bed preference (e.g., King, Twin, Double)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Travel desk who made the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was created', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='breakfast_included',
            field=models.BooleanField(default=False, help_text='Breakfast included'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Expected check-in time', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Expected check-out time', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, help_text='Date booking was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Hotel contact number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cost_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per night', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='dietary_requirements',
            field=models.TextField(blank=True, help_text='Dietary requirements for meals', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(blank=True, help_text='Hotel email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_chain',
            field=models.CharField(blank=True, help_text='Hotel chain (e.g., Marriott, Hilton)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='is_prepaid',
            field=models.BooleanField(default=False, help_text='Whether booking is prepaid'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='parking_included',
            field=models.BooleanField(default=False, help_text='Parking included'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='service_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charges', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='smoking_preference',
            field=models.BooleanField(default=False, help_text='Smoking room preference'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Special requests or requirements', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total booking cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='wifi_included',
            field=models.BooleanField(default=True, help_text='WiFi included'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline',
            field=models.CharField(help_text='Airline name', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='arrival_airport',
            field=models.CharField(help_text='Arrival airport name', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='arrival_time',
            field=models.DateTimeField(help_text='Scheduled arrival date and time'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', help_text='Cabin class', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(help_text='PNR/Booking reference', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Total booking cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='departure_airport',
            field=models.CharField(help_text='Departure airport name', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='departure_time',
            field=models.DateTimeField(help_text='Scheduled departure date and time'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight_number',
            field=models.CharField(help_text='Flight number (e.g., EK123)', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('TICKETED', 'Ticketed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('NO_SHOW', 'No Show')], default='PENDING', help_text='Current booking status', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='trf',
            field=models.ForeignKey(help_text='Travel request this booking is for', on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='trf.travelrequest'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='user',
            field=models.ForeignKey(help_text='Traveler for this booking', on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_reference',
            field=models.CharField(help_text='Hotel booking reference/confirmation number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(help_text='Check-in date'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_out_date',
            field=models.DateField(help_text='Check-out date'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(help_text='Hotel name', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='location',
            field=models.CharField(help_text='Hotel location/city', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(help_text='Room type (e.g., Standard, Deluxe, Suite)', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('TICKETED', 'Ticketed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('NO_SHOW', 'No Show')], default='PENDING', help_text='Current booking status', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='trf',
            field=models.ForeignKey(help_text='Travel request this booking is for', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='trf.travelrequest'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(help_text='Guest for this booking', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['trf', 'status'], name='bookings_fl_trf_id_61c6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['user', 'status'], name='bookings_fl_user_id_3ac935_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['booking_reference'], name='bookings_fl_booking_c05ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['departure_time'], name='bookings_fl_departu_647c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['trf', 'status'], name='bookings_ho_trf_id_2ec540_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['user', 'status'], name='bookings_ho_user_id_ea4647_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['booking_reference'], name='bookings_ho_booking_b5a323_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_ho_check_i_6a3b2c_idx'),
        ),
    ]
