# Generated by Django 5.2.16 on 2026-07-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0003_remove_hotelbooking_cost_flightbooking_airline_code_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HotelBooking",
        ),
    ]
