# Generated by Django 5.2.16 on 2026-08-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_delete_hotelbooking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightbooking",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="flightbooking",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="flightbooking",
            name="tax_amount",
        ),
    ]
