# Generated by Django 5.2.16 on 2026-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_flightbooking_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbooking",
            name="e_ticket",
            field=models.FileField(
                blank=True,
                help_text="Uploaded e-ticket document",
                null=True,
                upload_to="flight_tickets/",
            ),
        ),
        migrations.AddField(
            model_name="flightbooking",
            name="return_arrival_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Return leg scheduled arrival date and time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightbooking",
            name="return_departure_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Return leg scheduled departure date and time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flightbooking",
            name="return_flight_number",
            field=models.CharField(
                blank=True, help_text="Return flight number", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="flightbooking",
            name="airline",
            field=models.CharField(
                blank=True,
                help_text="Airline name. Required for Overseas travel; optional for Domestic (single-airline market) - enforced in the booking view, not at the DB level.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flightbooking",
            name="flight_number",
            field=models.CharField(
                help_text="Outbound flight number (e.g., EK123)", max_length=20
            ),
        ),
    ]
