# Generated by Django 5.2.16 on 2026-08-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_flightbooking_e_ticket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightBookingSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "Outbound"), ("RETURN", "Return")],
                        help_text="Outbound or return leg",
                        max_length=10,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="Order of this leg within its direction, starting at 1"
                    ),
                ),
                ("flight_number", models.CharField(max_length=20)),
                ("departure_airport", models.CharField(max_length=100)),
                ("arrival_airport", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="Booking this leg belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="bookings.flightbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["direction", "sequence"],
                "unique_together": {("booking", "direction", "sequence")},
            },
        ),
    ]
