# Generated by Django 5.2.16 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_flightbookingsegment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbooking",
            name="booking_reference",
            field=models.CharField(
                help_text="PNR/Booking reference. Not unique - the same PNR can legitimately cover multiple travelers on one booking.",
                max_length=50,
            ),
        ),
    ]
