# Generated by Django 5.0.2 on 2025-10-23 16:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('notification_count', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Unique identifier for the event type (e.g., 'trf_submitted')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(help_text='Category: approval, status_update, reminder, system', max_length=50)),
                ('module', models.CharField(help_text='Module: trf, visa, accommodation, transport, claims, general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_event_types',
                'ordering': ['module', 'category', 'name'],
                'indexes': [models.Index(fields=['category'], name='notificatio_categor_fca9a4_idx'), models.Index(fields=['module'], name='notificatio_module_d916b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('in_app_notifications_enabled', models.BooleanField(default=True, help_text='Receive in-app notifications')),
                ('push_notifications_enabled', models.BooleanField(default=False, help_text='Receive push notifications (future feature)')),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique template name identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Template description and purpose', null=True)),
                ('subject', models.TextField(help_text='Email subject line with variables like {userName}, {entityId}')),
                ('body', models.TextField(help_text='HTML email body template with variables')),
                ('notification_type', models.CharField(default='email', help_text='Type: email, system, or both', max_length=50)),
                ('recipient_type', models.CharField(default='approver', help_text='Recipient: approver, requestor, or both', max_length=50)),
                ('variables_available', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Array of available template variables', null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(blank=True, db_column='event_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='notifications.notificationeventtype')),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['event_type'], name='notificatio_event_t_b14530_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_9dff33_idx'), models.Index(fields=['recipient_type'], name='notificatio_recipie_28405a_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_f33840_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for the notification action', max_length=500, null=True)),
                ('action_text', models.CharField(default='View', help_text='Text for the action button', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('sent_via_push', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, help_text='Additional context data for the notification', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires and should be auto-archived', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationeventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_bf9fcb_idx'), models.Index(fields=['user', 'event_type'], name='notificatio_user_id_6e4199_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_2ca567_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_in_app', models.BooleanField(default=True)),
                ('receive_push', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='notifications.notificationeventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'event_type'],
                'unique_together': {('user', 'event_type')},
            },
        ),
    ]
