# Generated by Django 5.0.2 on 2025-11-15 02:10

from django.db import migrations


def create_notification_event_types(apps, schema_editor):
    """
    Create all notification event types for the comprehensive template library
    """
    NotificationEventType = apps.get_model('notifications', 'NotificationEventType')

    event_types = [
        {
            'name': 'WORKFLOW_STARTED',
            'description': '🔔 New workflow/request has been initiated and submitted for approval',
            'category': 'approval',
            'module': 'workflow',
        },
        {
            'name': 'STEP_ASSIGNED',
            'description': '📬 Action/approval step has been assigned to a user',
            'category': 'approval',
            'module': 'workflow',
        },
        {
            'name': 'APPROVAL_REQUESTED',
            'description': '❗ Approval is required from the current approver',
            'category': 'approval',
            'module': 'workflow',
        },
        {
            'name': 'APPROVAL_REMINDER',
            'description': '⏰ Reminder notification for pending approval (24h before SLA or overdue)',
            'category': 'reminder',
            'module': 'workflow',
        },
        {
            'name': 'ESCALATION',
            'description': '🚨 Request has been escalated due to SLA breach or delay',
            'category': 'escalation',
            'module': 'workflow',
        },
        {
            'name': 'REQUEST_RESUBMITTED',
            'description': '🔄 Request has been revised and resubmitted after rejection',
            'category': 'status_update',
            'module': 'workflow',
        },
        {
            'name': 'WORKFLOW_REJECTED',
            'description': '❌ Workflow/request has been rejected by an approver',
            'category': 'status_update',
            'module': 'workflow',
        },
        {
            'name': 'WORKFLOW_APPROVED',
            'description': '✅ Workflow has been fully approved and completed',
            'category': 'status_update',
            'module': 'workflow',
        },
        {
            'name': 'WORKFLOW_UPDATED',
            'description': 'Workflow status or details have been updated',
            'category': 'status_update',
            'module': 'workflow',
        },
        {
            'name': 'WORKFLOW_CANCELLED',
            'description': 'Workflow has been cancelled',
            'category': 'status_update',
            'module': 'workflow',
        },
        {
            'name': 'COMMENT_ADDED',
            'description': '💬 New comment has been added to the request',
            'category': 'collaboration',
            'module': 'workflow',
        },
        {
            'name': 'APPROVAL_DELEGATED',
            'description': '🤝 Approval has been delegated to another user',
            'category': 'approval',
            'module': 'workflow',
        },
    ]

    for event_data in event_types:
        NotificationEventType.objects.update_or_create(
            name=event_data['name'],
            defaults={
                'description': event_data['description'],
                'category': event_data['category'],
                'module': event_data['module'],
                'is_active': True,
            }
        )

    print(f"✅ Created {len(event_types)} notification event types")


def create_notification_templates(apps, schema_editor):
    """
    Create notification templates for each event type
    """
    NotificationEventType = apps.get_model('notifications', 'NotificationEventType')
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    templates = [
        {
            'name': 'workflow_started_requestor',
            'event_type_name': 'WORKFLOW_STARTED',
            'subject': '🔔 New Request Initiated - {{requestType}} #{{entityId}}',
            'body': '''Your {{requestType}} request #{{entityId}} has been submitted and is now in review.

Next: Approval by {{approverName}}. You'll be notified at each step.

→ Track progress: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'requestor',
            'variables_available': ['requestType', 'entityId', 'approverName', 'actionUrl'],
        },
        {
            'name': 'approval_required',
            'event_type_name': 'APPROVAL_REQUESTED',
            'subject': '❗ Pending Your Approval - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} requires your decision. Due: {{dueDate}}

{{urgencyHint}}

Requestor: {{requestorName}}

→ Review & act: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['requestType', 'entityId', 'dueDate', 'urgencyHint', 'requestorName', 'actionUrl'],
        },
        {
            'name': 'step_assigned',
            'event_type_name': 'STEP_ASSIGNED',
            'subject': '📬 Action Assigned to You - {{requestType}} #{{entityId}}',
            'body': '''You're now responsible for the next step on {{requestType}} #{{entityId}} (by {{requestorName}}).

{{processorHint}}

→ Review & act: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['requestType', 'entityId', 'requestorName', 'processorHint', 'actionUrl'],
        },
        {
            'name': 'approval_reminder',
            'event_type_name': 'APPROVAL_REMINDER',
            'subject': '{{reminderType}} - {{requestType}} #{{entityId}}',
            'body': '''{{reminderMessage}}

{{requestType}} #{{entityId}} {{statusMessage}}

→ Approve now | Delegate: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['reminderType', 'requestType', 'entityId', 'reminderMessage', 'statusMessage', 'actionUrl'],
        },
        {
            'name': 'escalation_required',
            'event_type_name': 'ESCALATION',
            'subject': '🚨 Escalation Required - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} is delayed beyond SLA at {{approverName}}.

Context: Assigned on {{assignedDate}}. No action in {{hoursNoAction}} hours. Requestor: {{requestorName}}.

→ View & intervene: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['requestType', 'entityId', 'approverName', 'assignedDate', 'hoursNoAction', 'requestorName', 'actionUrl'],
        },
        {
            'name': 'request_resubmitted',
            'event_type_name': 'REQUEST_RESUBMITTED',
            'subject': '🔄 Request Updated & Resubmitted - #{{entityId}}',
            'body': '''{{requestorName}} revised #{{entityId}} and resubmitted for your review.

{{changesSummary}}

→ Compare changes | Approve | Reject: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['entityId', 'requestorName', 'changesSummary', 'actionUrl'],
        },
        {
            'name': 'workflow_rejected',
            'event_type_name': 'WORKFLOW_REJECTED',
            'subject': '❌ Request Rejected - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} was rejected by {{approverName}}.

📝 Reason: "{{rejectionReason}}"

→ Revise & resubmit | Ask for clarification: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'requestor',
            'variables_available': ['requestType', 'entityId', 'approverName', 'rejectionReason', 'actionUrl'],
        },
        {
            'name': 'workflow_completed',
            'event_type_name': 'WORKFLOW_APPROVED',
            'subject': '✅ Request Completed - {{requestType}} #{{entityId}}',
            'body': '''Your {{requestType}} request #{{entityId}} has been processed successfully.

Finalized by {{processorName}} on {{completionDate}}

{{completionDetails}}

→ View details & documents: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'requestor',
            'variables_available': ['requestType', 'entityId', 'processorName', 'completionDate', 'completionDetails', 'actionUrl'],
        },
        {
            'name': 'new_comment_added',
            'event_type_name': 'COMMENT_ADDED',
            'subject': '💬 New Comment on #{{entityId}}{{mentionTag}}',
            'body': '''{{commenterName}}: "{{commentPreview}}"

{{mentionMessage}}

→ View full thread: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'both',
            'variables_available': ['entityId', 'commenterName', 'commentPreview', 'mentionMessage', 'mentionTag', 'actionUrl'],
        },
        {
            'name': 'delegation_confirmed',
            'event_type_name': 'APPROVAL_DELEGATED',
            'subject': '🤝 Delegation Confirmed - {{requestType}} #{{entityId}}',
            'body': '''{{delegatorName}} delegated {{requestType}} #{{entityId}} to you.

→ Review & approve: {{actionUrl}}''',
            'notification_type': 'both',
            'recipient_type': 'approver',
            'variables_available': ['delegatorName', 'requestType', 'entityId', 'actionUrl'],
        },
    ]

    created_count = 0
    for template_data in templates:
        event_type_name = template_data.pop('event_type_name')
        try:
            event_type = NotificationEventType.objects.get(name=event_type_name)
            NotificationTemplate.objects.update_or_create(
                name=template_data['name'],
                defaults={
                    **template_data,
                    'event_type': event_type,
                    'is_active': True,
                }
            )
            created_count += 1
        except NotificationEventType.DoesNotExist:
            print(f"⚠️ Event type {event_type_name} not found for template {template_data['name']}")

    print(f"✅ Created {created_count} notification templates")


def reverse_migration(apps, schema_editor):
    """
    Remove notification event types and templates
    """
    NotificationEventType = apps.get_model('notifications', 'NotificationEventType')
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    # Delete templates first (due to foreign key)
    NotificationTemplate.objects.filter(
        event_type__module='workflow'
    ).delete()

    # Delete event types
    NotificationEventType.objects.filter(module='workflow').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_notification_event_types, reverse_migration),
        migrations.RunPython(create_notification_templates, reverse_migration),
    ]
