# Generated by Django 5.0.2 on 2025-11-15 02:21

from django.db import migrations


def cleanup_unused_event_types(apps, schema_editor):
    """
    Remove unused event types that have no templates and no notifications
    """
    NotificationEventType = apps.get_model('notifications', 'NotificationEventType')
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    UserNotification = apps.get_model('notifications', 'UserNotification')

    # List of old/unused event types to remove
    unused_event_types = [
        'accommodation_submitted',
        'accommodation_approved',
        'accommodation_booked',
        'accommodation_rejected',
        'claim_submitted',
        'claim_approved_focal',
        'claim_approved_hod',
        'claim_approved_manager',
        'claim_paid',
        'claim_rejected',
        'deadline_reminder',
        'account_created',
        'password_reset',
        'system_maintenance',
        'transport_submitted',
        'transport_approved',
        'transport_rejected',
        'transport_scheduled',
        'trf_needs_booking',
        'trf_submitted',
        'trf_approved_focal',
        'trf_approved_hod',
        'trf_approved_manager',
        'trf_booking_completed',
        'trf_rejected',
        'visa_submitted',
        'visa_approved',
        'visa_processing',
        'visa_ready',
        'visa_rejected',
    ]

    deleted_count = 0
    for event_type_name in unused_event_types:
        try:
            event_type = NotificationEventType.objects.get(name=event_type_name)

            # Double check: only delete if no templates and no notifications
            has_templates = event_type.templates.exists()
            has_notifications = UserNotification.objects.filter(event_type=event_type).exists()

            if not has_templates and not has_notifications:
                event_type.delete()
                deleted_count += 1
                print(f"  ✓ Deleted unused event type: {event_type_name}")
            else:
                print(f"  ⚠ Skipped {event_type_name} - has templates or notifications")
        except NotificationEventType.DoesNotExist:
            # Already deleted or doesn't exist
            pass

    print(f"✅ Cleaned up {deleted_count} unused event types")


def reverse_cleanup(apps, schema_editor):
    """
    Reverse migration - recreate the deleted event types
    (They will be empty/unused, but at least the structure is restored)
    """
    NotificationEventType = apps.get_model('notifications', 'NotificationEventType')

    # Recreate basic event types (without templates)
    event_types_to_restore = [
        {'name': 'accommodation_submitted', 'category': 'status_update', 'module': 'accommodation'},
        {'name': 'accommodation_approved', 'category': 'status_update', 'module': 'accommodation'},
        {'name': 'accommodation_booked', 'category': 'status_update', 'module': 'accommodation'},
        {'name': 'accommodation_rejected', 'category': 'status_update', 'module': 'accommodation'},
        {'name': 'claim_submitted', 'category': 'status_update', 'module': 'claims'},
        {'name': 'claim_approved_focal', 'category': 'approval', 'module': 'claims'},
        {'name': 'claim_approved_hod', 'category': 'approval', 'module': 'claims'},
        {'name': 'claim_approved_manager', 'category': 'approval', 'module': 'claims'},
        {'name': 'claim_paid', 'category': 'status_update', 'module': 'claims'},
        {'name': 'claim_rejected', 'category': 'status_update', 'module': 'claims'},
        {'name': 'deadline_reminder', 'category': 'reminder', 'module': 'general'},
        {'name': 'account_created', 'category': 'system', 'module': 'general'},
        {'name': 'password_reset', 'category': 'system', 'module': 'general'},
        {'name': 'system_maintenance', 'category': 'system', 'module': 'general'},
        {'name': 'transport_submitted', 'category': 'status_update', 'module': 'transport'},
        {'name': 'transport_approved', 'category': 'approval', 'module': 'transport'},
        {'name': 'transport_rejected', 'category': 'status_update', 'module': 'transport'},
        {'name': 'transport_scheduled', 'category': 'status_update', 'module': 'transport'},
        {'name': 'trf_needs_booking', 'category': 'status_update', 'module': 'trf'},
        {'name': 'trf_submitted', 'category': 'status_update', 'module': 'trf'},
        {'name': 'trf_approved_focal', 'category': 'approval', 'module': 'trf'},
        {'name': 'trf_approved_hod', 'category': 'approval', 'module': 'trf'},
        {'name': 'trf_approved_manager', 'category': 'approval', 'module': 'trf'},
        {'name': 'trf_booking_completed', 'category': 'status_update', 'module': 'trf'},
        {'name': 'trf_rejected', 'category': 'status_update', 'module': 'trf'},
        {'name': 'visa_submitted', 'category': 'status_update', 'module': 'visa'},
        {'name': 'visa_approved', 'category': 'approval', 'module': 'visa'},
        {'name': 'visa_processing', 'category': 'status_update', 'module': 'visa'},
        {'name': 'visa_ready', 'category': 'status_update', 'module': 'visa'},
        {'name': 'visa_rejected', 'category': 'status_update', 'module': 'visa'},
    ]

    for event_data in event_types_to_restore:
        NotificationEventType.objects.get_or_create(
            name=event_data['name'],
            defaults={
                'description': f"{event_data['name'].replace('_', ' ').title()}",
                'category': event_data['category'],
                'module': event_data['module'],
                'is_active': False,  # Restored but inactive
            }
        )

    print(f"✅ Restored {len(event_types_to_restore)} event types")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_setup_notification_templates'),
    ]

    operations = [
        migrations.RunPython(cleanup_unused_event_types, reverse_cleanup),
    ]
