# Generated by Claude Code on 2026-01-06

from django.db import migrations


def update_notification_templates(apps, schema_editor):
    """
    Update all notification templates with improved professional content
    Based on IMPROVED_NOTIFICATION_TEMPLATES.md specifications
    """
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    template_updates = [
        # 1. Workflow Started (for the requestor)
        {
            'name': 'workflow_started_requestor',
            'subject': '✅ Your {{requestType}} Request (#{{entityId}}) Has Been Submitted',
            'body': '''Hi {{requestorName}},

This email confirms that your **{{requestType}}** request (ID: **#{{entityId}}**) has been successfully submitted and is now pending review.

**Next Steps:**
*   The request has been assigned to **{{approverName}}** for approval.
*   You will receive further notifications as your request progresses through the workflow.

[Track Progress]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['requestorName', 'requestType', 'entityId', 'approverName', 'actionUrl'],
        },

        # 2. Approval Required (for the approver)
        {
            'name': 'approval_required',
            'subject': 'Action Required: Approve {{requestType}} Request #{{entityId}}',
            'body': '''Hi {{approverName}},

A **{{requestType}}** request (ID: **#{{entityId}}**) from **{{requestorName}}** requires your approval.

**Details:**
*   **Requestor:** {{requestorName}}
*   **Due Date:** {{dueDate}}
*   **Urgency:** {{urgencyHint}}

Please review the request and take action by the due date.

[Review & Approve]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['approverName', 'requestType', 'entityId', 'requestorName', 'dueDate', 'urgencyHint', 'actionUrl'],
        },

        # 3. Step Assigned
        {
            'name': 'step_assigned',
            'subject': 'Task Assigned: {{requestType}} Request #{{entityId}}',
            'body': '''Hi {{approverName}},

You have been assigned a new task for the **{{requestType}}** request (ID: **#{{entityId}}**) submitted by **{{requestorName}}**.

**Task Details:**
*   {{processorHint}}

Please complete your task to move the request to the next step.

[View Task]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['approverName', 'requestType', 'entityId', 'requestorName', 'processorHint', 'actionUrl'],
        },

        # 4. Approval Reminder
        {
            'name': 'approval_reminder',
            'subject': 'Reminder: Action Required for {{requestType}} Request #{{entityId}}',
            'body': '''Hi {{approverName}},

This is a {{reminderType}} for the **{{requestType}}** request (ID: **#{{entityId}}**).

**Status:** {{statusMessage}}

{{reminderMessage}}

Please take action to avoid delays.

[Approve or Delegate]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['approverName', 'reminderType', 'requestType', 'entityId', 'reminderMessage', 'statusMessage', 'actionUrl'],
        },

        # 5. Escalation Required
        {
            'name': 'escalation_required',
            'subject': 'Escalation: {{requestType}} Request #{{entityId}} is Overdue',
            'body': '''Hi {{managerName}},

The **{{requestType}}** request (ID: **#{{entityId}}**) has been escalated due to a delay in the approval process.

**Details:**
*   **Requestor:** {{requestorName}}
*   **Current Approver:** {{approverName}}
*   **Assigned On:** {{assignedDate}}
*   **Delayed By:** {{hoursNoAction}} hours

Please intervene to ensure the request is processed.

[View Request and Take Action]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['managerName', 'requestType', 'entityId', 'requestorName', 'approverName', 'assignedDate', 'hoursNoAction', 'actionUrl'],
        },

        # 6. Request Resubmitted
        {
            'name': 'request_resubmitted',
            'subject': 'Request #{{entityId}} Has Been Updated and Resubmitted',
            'body': '''Hi {{approverName}},

The request **#{{entityId}}** from **{{requestorName}}** has been updated and is ready for your review.

**Summary of Changes:**
{{changesSummary}}

Please review the changes and take action.

[Review Changes and Approve/Reject]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['approverName', 'entityId', 'requestorName', 'changesSummary', 'actionUrl'],
        },

        # 7. Workflow Rejected
        {
            'name': 'workflow_rejected',
            'subject': 'Update on Your {{requestType}} Request #{{entityId}}',
            'body': '''Hi {{requestorName}},

Your **{{requestType}}** request (ID: **#{{entityId}}**) was rejected by **{{approverName}}**.

**Reason for Rejection:**
"{{rejectionReason}}"

You can revise and resubmit your request, or contact the approver for clarification.

[View and Revise Request]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['requestorName', 'requestType', 'entityId', 'approverName', 'rejectionReason', 'actionUrl'],
        },

        # 8. Workflow Approved/Completed
        {
            'name': 'workflow_completed',
            'subject': 'Your {{requestType}} Request #{{entityId}} Has Been Approved',
            'body': '''Hi {{requestorName}},

Great news! Your **{{requestType}}** request (ID: **#{{entityId}}**) has been fully approved and processed.

**Summary:**
*   **Finalized By:** {{processorName}}
*   **Completion Date:** {{completionDate}}
*   **Details:** {{completionDetails}}

You can view the final details and any related documents by clicking the link below.

[View Request Details]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['requestorName', 'requestType', 'entityId', 'processorName', 'completionDate', 'completionDetails', 'actionUrl'],
        },

        # 9. New Comment Added
        {
            'name': 'new_comment_added',
            'subject': 'New Comment on Request #{{entityId}}',
            'body': '''Hi {{userName}},

A new comment has been added to the request **#{{entityId}}**.

**{{commenterName}}** wrote:
"{{commentPreview}}..."

{{mentionMessage}}

[View Full Conversation]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['userName', 'entityId', 'commenterName', 'commentPreview', 'mentionMessage', 'mentionTag', 'actionUrl'],
        },

        # 10. Delegation Confirmed
        {
            'name': 'delegation_confirmed',
            'subject': 'A {{requestType}} Request Has Been Delegated to You',
            'body': '''Hi {{approverName}},

**{{delegatorName}}** has delegated a **{{requestType}}** request (ID: **#{{entityId}}**) to you for approval.

Please review the request and take action.

[Review and Approve]({{actionUrl}})

Thank you,
The TMS Team''',
            'variables_available': ['approverName', 'delegatorName', 'requestType', 'entityId', 'actionUrl'],
        },
    ]

    updated_count = 0
    errors = []

    for template_data in template_updates:
        try:
            template = NotificationTemplate.objects.get(name=template_data['name'])
            template.subject = template_data['subject']
            template.body = template_data['body']
            template.variables_available = template_data['variables_available']
            template.save()
            updated_count += 1
            print(f"✅ Updated template: {template_data['name']}")
        except NotificationTemplate.DoesNotExist:
            error_msg = f"⚠️ Template not found: {template_data['name']}"
            errors.append(error_msg)
            print(error_msg)
        except Exception as e:
            error_msg = f"❌ Error updating {template_data['name']}: {str(e)}"
            errors.append(error_msg)
            print(error_msg)

    print(f"\n{'='*60}")
    print(f"✅ Successfully updated {updated_count} out of {len(template_updates)} templates")
    if errors:
        print(f"⚠️  {len(errors)} errors occurred:")
        for error in errors:
            print(f"   {error}")
    print(f"{'='*60}\n")


def reverse_update_templates(apps, schema_editor):
    """
    Reverse migration - restore original template content
    Note: This will restore the templates to their state before this migration
    """
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    # Original template content from 0002_setup_notification_templates.py
    original_templates = [
        {
            'name': 'workflow_started_requestor',
            'subject': '🔔 New Request Initiated - {{requestType}} #{{entityId}}',
            'body': '''Your {{requestType}} request #{{entityId}} has been submitted and is now in review.

Next: Approval by {{approverName}}. You'll be notified at each step.

→ Track progress: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'approverName', 'actionUrl'],
        },
        {
            'name': 'approval_required',
            'subject': '❗ Pending Your Approval - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} requires your decision. Due: {{dueDate}}

{{urgencyHint}}

Requestor: {{requestorName}}

→ Review & act: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'dueDate', 'urgencyHint', 'requestorName', 'actionUrl'],
        },
        {
            'name': 'step_assigned',
            'subject': '📬 Action Assigned to You - {{requestType}} #{{entityId}}',
            'body': '''You're now responsible for the next step on {{requestType}} #{{entityId}} (by {{requestorName}}).

{{processorHint}}

→ Review & act: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'requestorName', 'processorHint', 'actionUrl'],
        },
        {
            'name': 'approval_reminder',
            'subject': '{{reminderType}} - {{requestType}} #{{entityId}}',
            'body': '''{{reminderMessage}}

{{requestType}} #{{entityId}} {{statusMessage}}

→ Approve now | Delegate: {{actionUrl}}''',
            'variables_available': ['reminderType', 'requestType', 'entityId', 'reminderMessage', 'statusMessage', 'actionUrl'],
        },
        {
            'name': 'escalation_required',
            'subject': '🚨 Escalation Required - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} is delayed beyond SLA at {{approverName}}.

Context: Assigned on {{assignedDate}}. No action in {{hoursNoAction}} hours. Requestor: {{requestorName}}.

→ View & intervene: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'approverName', 'assignedDate', 'hoursNoAction', 'requestorName', 'actionUrl'],
        },
        {
            'name': 'request_resubmitted',
            'subject': '🔄 Request Updated & Resubmitted - #{{entityId}}',
            'body': '''{{requestorName}} revised #{{entityId}} and resubmitted for your review.

{{changesSummary}}

→ Compare changes | Approve | Reject: {{actionUrl}}''',
            'variables_available': ['entityId', 'requestorName', 'changesSummary', 'actionUrl'],
        },
        {
            'name': 'workflow_rejected',
            'subject': '❌ Request Rejected - {{requestType}} #{{entityId}}',
            'body': '''{{requestType}} #{{entityId}} was rejected by {{approverName}}.

📝 Reason: "{{rejectionReason}}"

→ Revise & resubmit | Ask for clarification: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'approverName', 'rejectionReason', 'actionUrl'],
        },
        {
            'name': 'workflow_completed',
            'subject': '✅ Request Completed - {{requestType}} #{{entityId}}',
            'body': '''Your {{requestType}} request #{{entityId}} has been processed successfully.

Finalized by {{processorName}} on {{completionDate}}

{{completionDetails}}

→ View details & documents: {{actionUrl}}''',
            'variables_available': ['requestType', 'entityId', 'processorName', 'completionDate', 'completionDetails', 'actionUrl'],
        },
        {
            'name': 'new_comment_added',
            'subject': '💬 New Comment on #{{entityId}}{{mentionTag}}',
            'body': '''{{commenterName}}: "{{commentPreview}}"

{{mentionMessage}}

→ View full thread: {{actionUrl}}''',
            'variables_available': ['entityId', 'commenterName', 'commentPreview', 'mentionMessage', 'mentionTag', 'actionUrl'],
        },
        {
            'name': 'delegation_confirmed',
            'subject': '🤝 Delegation Confirmed - {{requestType}} #{{entityId}}',
            'body': '''{{delegatorName}} delegated {{requestType}} #{{entityId}} to you.

→ Review & approve: {{actionUrl}}''',
            'variables_available': ['delegatorName', 'requestType', 'entityId', 'actionUrl'],
        },
    ]

    reverted_count = 0
    for template_data in original_templates:
        try:
            template = NotificationTemplate.objects.get(name=template_data['name'])
            template.subject = template_data['subject']
            template.body = template_data['body']
            template.variables_available = template_data['variables_available']
            template.save()
            reverted_count += 1
            print(f"↩️  Reverted template: {template_data['name']}")
        except NotificationTemplate.DoesNotExist:
            print(f"⚠️ Template not found during rollback: {template_data['name']}")

    print(f"\n{'='*60}")
    print(f"↩️  Successfully reverted {reverted_count} templates to original state")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_cleanup_unused_event_types'),
    ]

    operations = [
        migrations.RunPython(update_notification_templates, reverse_update_templates),
    ]
