# Generated by Django 5.2.17 on 2026-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_remove_urgency_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
