# Generated by Django 5.2.17 on 2026-09-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_delete_stale_read_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotification",
            name="push_sent_at",
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="sent_via_push",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="digest_frequency",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="push_notifications_enabled",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="quiet_hours_enabled",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="quiet_hours_end",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="quiet_hours_start",
        ),
        migrations.RemoveField(
            model_name="usernotificationsubscription",
            name="receive_push",
        ),
    ]
