trigger:
  branches:
    include:
      - main
      - master
      - develop
      - chore/*

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0

- script: |
    echo "===== DEBUG INFO ====="
    echo "Token length is: ${#AZURE_DEVOPS_PAT}"
    echo "First 8 characters: ${AZURE_DEVOPS_PAT:0:8}"
    echo "======================"

    git config --global user.email "azure-mirror@pipeline"
    git config --global user.name "Azure Repos Mirror"

    git remote add azure https://anything:$(AZURE_DEVOPS_PAT)@dev.azure.com/arslantekayev/Travel%20Management%20System/_git/Travel%20Management%20System

    git push azure --all --force
    git push azure --tags --force
  displayName: 'Mirror GitHub → Azure Repos'
  env:
    AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)