# Generated by Django 5.0.2 on 2025-10-14 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=50)),
                ('current_step_order', models.IntegerField(default=1, help_text='Current step order being executed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, help_text='Additional context data for workflow execution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('step_completed', 'Step Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('cancelled', 'Cancelled'), ('on_hold', 'Put On Hold'), ('resumed', 'Resumed'), ('escalated', 'Escalated')], max_length=50)),
                ('action_description', models.TextField()),
                ('workflow_state_snapshot', models.JSONField(blank=True, help_text='JSON snapshot of workflow state when action was performed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.workflowinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Order in which this step should be executed (1, 2, 3, ...)')),
                ('step_name', models.CharField(max_length=255)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('approver_role', models.CharField(help_text="Role name required to approve this step (e.g., 'HOD', 'Finance')", max_length=100)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this step must be completed for workflow to proceed')),
                ('can_skip', models.BooleanField(default=False, help_text='Whether this step can be skipped')),
                ('requires_comments', models.BooleanField(default=False, help_text='Whether approver must provide comments')),
                ('sla_hours', models.IntegerField(blank=True, help_text='Service Level Agreement - expected hours to complete this step', null=True)),
                ('escalation_hours', models.IntegerField(blank=True, help_text='Hours before escalation notification is sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user assigned to this step (optional, overrides role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow_template', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('field_equals', 'Field Equals'), ('field_greater_than', 'Field Greater Than'), ('field_less_than', 'Field Less Than'), ('field_contains', 'Field Contains'), ('field_exists', 'Field Exists'), ('custom_logic', 'Custom Logic')], max_length=50)),
                ('field_name', models.CharField(help_text='Name of the field to check on the entity', max_length=100)),
                ('field_value', models.CharField(blank=True, help_text='Value to compare against', max_length=255, null=True)),
                ('logical_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', help_text='How to combine multiple conditions', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflows.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('delegated', 'Delegated')], default='pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('sla_due_date', models.DateTimeField(blank=True, null=True)),
                ('escalation_date', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actioned_by', models.ForeignKey(blank=True, help_text='User who took action on this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_actioned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='User assigned to complete this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='workflows.workflowinstance')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['workflow_instance', 'workflow_step__step_order'],
                'unique_together': {('workflow_instance', 'workflow_step')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delegated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When delegation expires (null = no expiry)', null=True)),
                ('delegated_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_made', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('workflow_step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='workflows.workflowstepexecution')),
            ],
            options={
                'ordering': ['-delegated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(help_text="Type of entity this workflow applies to (e.g., 'trf', 'visa', 'transport')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_parallel_steps', models.BooleanField(default=False, help_text='Allow multiple steps to be active simultaneously')),
                ('auto_approve_on_condition', models.BooleanField(default=False, help_text='Automatically approve steps when conditions are met')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow_template', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_9e540a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'current_step_order'], name='workflows_w_status_741221_idx'),
        ),
    ]
