# Generated by Django 5.0.2 on 2025-11-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_cleanup_unused_event_types'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assignment', 'On Step Assignment'), ('approval', 'On Approval'), ('rejection', 'On Rejection'), ('escalation', 'On Escalation'), ('reminder', 'On Reminder'), ('delegation', 'On Delegation')], help_text='Workflow event that triggers this notification', max_length=50)),
                ('recipient_types', models.JSONField(default=list, help_text="List of recipient types (e.g., ['current_approver', 'requester'])")),
                ('custom_recipients', models.JSONField(blank=True, default=list, help_text='List of custom email addresses')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification configuration is active')),
                ('send_email', models.BooleanField(default=True, help_text='Send as email notification')),
                ('send_system_notification', models.BooleanField(default=True, help_text='Send as in-app system notification')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notification priority level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_template', models.ForeignKey(help_text='Template to use for this notification', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_configs', to='notifications.notificationtemplate')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow Step Notification Configuration',
                'verbose_name_plural': 'Workflow Step Notification Configurations',
                'ordering': ['workflow_step', 'event_type'],
            },
        ),
    ]
