# Generated by Django 5.0.2 on 2025-11-17 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstepnotificationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='approver_permission',
            field=models.CharField(blank=True, help_text="Permission required to approve this step (e.g., 'approve_transport', 'approve_trf'). Preferred over approver_role.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_role',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Role name required to approve this step - use approver_permission instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='Specific user assigned to this step (optional, overrides permission/role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
