# Generated by Django 5.2.8 on 2025-12-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_cleanup_unused_event_types'),
        ('workflows', '0004_add_notification_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstepnotificationconfig',
            options={'ordering': ['workflow_step', 'event_type'], 'verbose_name': 'Workflow Step Notification Configuration', 'verbose_name_plural': 'Workflow Step Notification Configurations'},
        ),
        migrations.RemoveIndex(
            model_name='workflowstepnotificationconfig',
            name='workflow_st_workflo_9067f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowstepnotificationconfig',
            name='workflow_st_is_acti_1ac893_idx',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='bcc_roles',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='bcc_users',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='cc_next_approver',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='cc_previous_approvers',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='cc_requestor',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='cc_roles',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='cc_users',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='custom_subject',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='recipient_roles',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='recipient_users',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='send_in_app',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='send_push',
        ),
        migrations.RemoveField(
            model_name='workflowstepnotificationconfig',
            name='trigger_event',
        ),
        migrations.AddField(
            model_name='workflowstepnotificationconfig',
            name='custom_recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of custom email addresses'),
        ),
        migrations.AddField(
            model_name='workflowstepnotificationconfig',
            name='event_type',
            field=models.CharField(choices=[('assignment', 'On Step Assignment'), ('approval', 'On Approval'), ('rejection', 'On Rejection'), ('escalation', 'On Escalation'), ('reminder', 'On Reminder'), ('delegation', 'On Delegation')], default='assignment', help_text='Workflow event that triggers this notification', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowstepnotificationconfig',
            name='recipient_types',
            field=models.JSONField(default=list, help_text="List of recipient types (e.g., ['current_approver', 'requester'])"),
        ),
        migrations.AddField(
            model_name='workflowstepnotificationconfig',
            name='send_system_notification',
            field=models.BooleanField(default=True, help_text='Send as in-app system notification'),
        ),
        migrations.AlterField(
            model_name='workflowstepnotificationconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this notification configuration is active'),
        ),
        migrations.AlterField(
            model_name='workflowstepnotificationconfig',
            name='notification_template',
            field=models.ForeignKey(help_text='Template to use for this notification', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_configs', to='notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='workflowstepnotificationconfig',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='workflows.workflowstep'),
        ),
        migrations.AlterModelTable(
            name='workflowstepnotificationconfig',
            table=None,
        ),
    ]
