# Generated by Django 5.2.8 on 2026-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflowstepnotificationconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepnotificationconfig',
            name='event_type',
            field=models.CharField(choices=[('assignment', 'On Step Assignment'), ('approval', 'On Step Approval'), ('rejection', 'On Step Rejection'), ('escalation', 'On Step Escalation'), ('reminder', 'Reminder Notification'), ('delegation', 'On Step Delegation'), ('workflow_completed', 'When All Approvals Complete'), ('workflow_cancelled', 'When Workflow Cancelled')], default='assignment', help_text='Workflow event that triggers this notification', max_length=50),
        ),
    ]
