# Generated by Django 5.0.2 on 2026-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0009_enable_can_skip_for_all_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="can_skip",
            field=models.BooleanField(
                default=True,
                help_text="Whether this step can be skipped when no approver is available",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("skipped", "Skipped"),
                    ("delegated", "Delegated"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
