# Generated by Django 5.2.16 on 2026-07-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0012_fix_travelrequest_can_skip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstep",
            name="escalation_hours",
        ),
        migrations.RemoveField(
            model_name="workflowstepexecution",
            name="escalation_date",
        ),
        migrations.RemoveField(
            model_name="workflowstepexecution",
            name="is_escalated",
        ),
        migrations.AlterField(
            model_name="workflowauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("started", "Started"),
                    ("step_completed", "Step Completed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("delegated", "Delegated"),
                    ("cancelled", "Cancelled"),
                    ("on_hold", "Put On Hold"),
                    ("resumed", "Resumed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepnotificationconfig",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment", "On Step Assignment"),
                    ("approval", "On Step Approval"),
                    ("rejection", "On Step Rejection"),
                    ("reminder", "Reminder Notification"),
                    ("delegation", "On Step Delegation"),
                    ("workflow_completed", "When All Approvals Complete"),
                    ("workflow_cancelled", "When Workflow Cancelled"),
                ],
                default="assignment",
                help_text="Workflow event that triggers this notification",
                max_length=50,
            ),
        ),
    ]
