# Generated by Django 5.2.16 on 2026-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0013_remove_workflowstep_escalation_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstepexecution",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the one-shot 'reminder' notification was sent for this step execution's SLA window (send_step_reminders management command). Null if not yet sent.",
                null=True,
            ),
        ),
    ]
