# Generated by Django 5.2.17 on 2026-08-20 21:39
"""
Removes the SLA due-date / overdue tracking mechanism entirely: the
send_step_reminders cron job it powered has been deleted, its "reminder"
event type is no longer a valid WorkflowStepNotificationConfig choice, and
sla_hours was never surfaced anywhere except that job and the removed
"Due Date" text in a couple of notification emails.
"""

from django.db import migrations, models


def remove_orphaned_reminder_configs(apps, schema_editor):
    """
    Existing WorkflowStepNotificationConfig rows with event_type='reminder'
    are now unreachable - nothing triggers that event type anymore (the
    'reminder' choice is removed by this same migration) - so they're just
    orphaned config data pointing at a step's now-defunct reminder setup.
    """
    WorkflowStepNotificationConfig = apps.get_model(
        "workflows", "WorkflowStepNotificationConfig"
    )
    WorkflowStepNotificationConfig.objects.filter(event_type="reminder").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0017_remove_combined_request_workflow_template"),
    ]

    operations = [
        migrations.RunPython(
            remove_orphaned_reminder_configs, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="workflowstep",
            name="sla_hours",
        ),
        migrations.RemoveField(
            model_name="workflowstepexecution",
            name="is_overdue",
        ),
        migrations.RemoveField(
            model_name="workflowstepexecution",
            name="reminder_sent_at",
        ),
        migrations.RemoveField(
            model_name="workflowstepexecution",
            name="sla_due_date",
        ),
        migrations.AlterField(
            model_name="workflowstepnotificationconfig",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment", "On Step Assignment"),
                    ("approval", "On Step Approval"),
                    ("rejection", "On Step Rejection"),
                    ("delegation", "On Step Delegation"),
                    ("workflow_completed", "When All Approvals Complete"),
                    ("workflow_cancelled", "When Workflow Cancelled"),
                ],
                default="assignment",
                help_text="Workflow event that triggers this notification",
                max_length=50,
            ),
        ),
    ]
