# Generated by Django 5.2.17 on 2026-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0022_seed_processing_completed_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstepnotificationconfig",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assignment", "On Step Assignment"),
                    ("approval", "On Step Approval"),
                    ("rejection", "On Step Rejection"),
                    ("delegation", "On Step Delegation"),
                    ("workflow_started", "When Workflow Starts"),
                    ("workflow_completed", "When All Approvals Complete"),
                    ("workflow_cancelled", "When Workflow Cancelled"),
                    ("processing_completed", "When Processing Is Marked Complete"),
                ],
                default="assignment",
                help_text="Workflow event that triggers this notification",
                max_length=50,
            ),
        ),
    ]
