# Generated by Django 5.2.17 on 2026-08-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0024_seed_workflow_started_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False means this step was removed from the workflow configuration (e.g. step count reduced) but is kept because past workflow instances have execution history against it. Inactive steps are excluded from step counts, live workflow progression, and the editable step list, and are reactivated automatically if a future edit reintroduces the same step_order.",
            ),
        ),
    ]
