# Generated by Django 5.2.17 on 2026-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0031_cleanup_orphaned_homeleave_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
