# Generated by Django 5.2.17 on 2026-09-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0034_approver_permission_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="workflow_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="workflows.workflowtemplate",
            ),
        ),
    ]
