# Generated by Django 5.2.17 on 2026-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0035_protect_workflowinstance_template_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="object_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
