# Generated by Django 5.0.2 on 2025-10-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        ('trf', '0002_travelrequest_remove_travelrequestform_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='trf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trf.travelrequest'),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodationroom'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='staff_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodationstaffhouse'),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='staff_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodationstaffhouse'),
        ),
        migrations.AlterUniqueTogether(
            name='accommodationbooking',
            unique_together={('room', 'date')},
        ),
    ]
