# Generated by Django 5.0.2 on 2025-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationrequest',
            name='status',
            field=models.CharField(default='Draft', help_text='Dynamic status set by workflow engine', max_length=100),
        ),
    ]
