# Generated by Django 5.0.2 on 2025-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_update_status_for_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='request_number',
            field=models.CharField(blank=True, help_text='Auto-generated request number (e.g., ACCOM-20251102-1423-DFS-PCYX)', max_length=50, null=True, unique=True),
        ),
    ]
