# Generated by Django 5.0.2 on 2025-11-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_add_request_number_to_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationrequest',
            name='estimated_cost',
        ),
    ]
