# Generated by Django 5.0.2 on 2025-11-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_remove_estimated_cost'),
        ('trf', '0005_travelrequest_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='trf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_requests', to='trf.travelrequest'),
        ),
    ]
