# Generated by Django 5.0.2 on 2025-11-24 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_accommodationrequest_trf'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='accommodation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.accommodationrequest'),
        ),
    ]
