# Generated by Django 5.2.8 on 2025-12-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_accommodationbooking_accommodation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this accommodation request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
