# Generated by Django 5.2.8 on 2025-12-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_accommodationrequest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationrequest',
            name='created_by',
        ),
    ]
