# Generated by Django 5.0.2 on 2025-10-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('travel_purpose', models.TextField()),
                ('visa_type', models.CharField(max_length=255)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending Department Focal', max_length=255)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trf_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_details', models.JSONField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_place_of_issuance', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_date_of_issuance', models.DateField(blank=True, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('education_details', models.TextField(blank=True, null=True)),
                ('current_employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_employer_address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('family_information', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(default='VISA', max_length=255)),
                ('approximately_arrival_date', models.DateField(blank=True, null=True)),
                ('duration_of_stay', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_entry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('work_visit_category', models.CharField(blank=True, max_length=255, null=True)),
                ('application_fees_borne_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_centre_number', models.CharField(blank=True, max_length=255, null=True)),
                ('line_focal_person', models.CharField(blank=True, max_length=255, null=True)),
                ('line_focal_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('line_focal_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('line_focal_date', models.DateField(blank=True, null=True)),
                ('sponsoring_dept_head', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsoring_dept_head_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsoring_dept_head_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsoring_dept_head_date', models.DateField(blank=True, null=True)),
                ('ceo_approval_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_approval_date', models.DateField(blank=True, null=True)),
                ('itinerary_details', models.TextField(blank=True, null=True)),
                ('supporting_documents_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.visaapplication')),
            ],
        ),
        migrations.CreateModel(
            name='VisaApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_role', models.CharField(max_length=255)),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('step_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.visaapplication')),
            ],
            options={
                'unique_together': {('visa', 'step_role')},
            },
        ),
    ]
