# Generated by Django 5.0.2 on 2025-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visaapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaapprovalstep',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='visaapprovalstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='status',
            field=models.CharField(default='Draft', help_text='Dynamic status set by workflow engine', max_length=100),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapprovalstep',
            name='step_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
