# Generated by Django 5.0.2 on 2025-11-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_change_status_to_workflow_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='request_number',
            field=models.CharField(blank=True, help_text='Auto-generated request number (e.g., VIS-20251102-1423-TKM-PCYX)', max_length=50, null=True, unique=True),
        ),
    ]
