# Generated by Django 5.2.17 on 2026-09-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0004_add_passport_file_to_visa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visaapplication",
            name="ceo_approval_date",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="ceo_approval_name",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="line_focal_contact",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="line_focal_date",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="line_focal_dept",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="line_focal_person",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="sponsoring_dept_head",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="sponsoring_dept_head_contact",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="sponsoring_dept_head_date",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="sponsoring_dept_head_dept",
        ),
    ]
