# Generated by Django 5.2.17 on 2026-09-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0005_remove_dead_embedded_approval_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="processing_completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visa_applications_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
