# Generated by Django 5.0.2 on 2025-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_deprecated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(default='Draft', help_text='Dynamic status set by workflow engine', max_length=100),
        ),
    ]
