# Generated by Django 5.0.2 on 2025-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='request_number',
            field=models.CharField(blank=True, help_text='Auto-generated request number (e.g., TRN-20251102-1423-ASH-PCYX)', max_length=50, null=True, unique=True),
        ),
    ]
