# Generated by Django 5.2.16 on 2026-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0006_add_request_number_to_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleassignment",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
