# Generated by Django 5.2.16 on 2026-08-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0007_alter_vehicleassignment_vehicle_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransportSegment",
        ),
    ]
