# Generated migration for Combined Request models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, help_text='Auto-generated request number (e.g., CMB-20250415-0930-DXB-A7K2)', max_length=50, null=True, unique=True)),
                ('requestor_name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('include_travel', models.BooleanField(default=True, help_text='Include Travel/TSR in this request')),
                ('include_transport', models.BooleanField(default=False, help_text='Include Transport in this request')),
                ('include_accommodation', models.BooleanField(default=False, help_text='Include Accommodation in this request')),
                ('include_visa', models.BooleanField(default=False, help_text='Include Visa in this request')),
                ('travel_type', models.CharField(blank=True, help_text='Type: domestic, international, home_leave, external', max_length=50, null=True)),
                ('travel_purpose', models.TextField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('travel_data', models.JSONField(blank=True, default=dict, help_text='Additional travel-specific data (meal selections, advance requests, etc.)')),
                ('transport_required_from', models.DateTimeField(blank=True, null=True)),
                ('transport_required_to', models.DateTimeField(blank=True, null=True)),
                ('transport_pickup_location', models.CharField(blank=True, max_length=500, null=True)),
                ('transport_dropoff_location', models.CharField(blank=True, max_length=500, null=True)),
                ('transport_data', models.JSONField(blank=True, default=dict, help_text='Additional transport data (vehicle preferences, special requirements)')),
                ('accommodation_checkin', models.DateField(blank=True, null=True)),
                ('accommodation_checkout', models.DateField(blank=True, null=True)),
                ('accommodation_location', models.CharField(blank=True, max_length=500, null=True)),
                ('accommodation_guests', models.IntegerField(default=1)),
                ('accommodation_preferences', models.TextField(blank=True, null=True)),
                ('accommodation_data', models.JSONField(blank=True, default=dict, help_text='Additional accommodation data (room type, special requests)')),
                ('visa_destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_data', models.JSONField(blank=True, default=dict, help_text='Additional visa data (previous visas, sponsor info, etc.)')),
                ('status', models.CharField(default='Draft', help_text='Overall workflow status set by workflow engine', max_length=100)),
                ('travel_status', models.CharField(default='pending', help_text='Travel module status: not_requested, pending, approved, processing, completed', max_length=50)),
                ('transport_status', models.CharField(default='not_requested', help_text='Transport module status', max_length=50)),
                ('accommodation_status', models.CharField(default='not_requested', help_text='Accommodation module status', max_length=50)),
                ('visa_status', models.CharField(default='not_requested', help_text='Visa module status', max_length=50)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Flexible storage for workflow data (selected_approvers, skipped_steps, etc.)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Combined Request',
                'verbose_name_plural': 'Combined Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombinedRequestApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('step_role', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(blank=True, help_text='Which module this step is for (travel, transport, accommodation, visa, or null for general)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('combined_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='combined_request.combinedrequest')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='CombinedRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Copy'), ('visa_photo', 'Visa Photo'), ('invitation_letter', 'Invitation Letter'), ('flight_ticket', 'Flight Ticket'), ('hotel_booking', 'Hotel Booking'), ('travel_insurance', 'Travel Insurance'), ('supporting_doc', 'Supporting Document'), ('other', 'Other')], max_length=50)),
                ('module', models.CharField(choices=[('travel', 'Travel'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('visa', 'Visa'), ('general', 'General')], default='general', max_length=20)),
                ('file', models.FileField(upload_to='combined_request/documents/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('combined_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='combined_request.combinedrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['module', 'document_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CombinedRequestItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_order', models.PositiveIntegerField(default=1)),
                ('segment_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('mode_of_travel', models.CharField(blank=True, help_text='flight, train, bus, car, etc.', max_length=50, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_class', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_segments', to='combined_request.combinedrequest')),
            ],
            options={
                'verbose_name': 'Itinerary Segment',
                'verbose_name_plural': 'Itinerary Segments',
                'ordering': ['segment_order', 'segment_date'],
            },
        ),
        migrations.CreateModel(
            name='CombinedRequestPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('passport_file', models.FileField(blank=True, help_text='Uploaded passport scan/photo', null=True, upload_to='combined_request/passports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='combined_request.combinedrequest')),
            ],
            options={
                'verbose_name': 'Passport Detail',
                'verbose_name_plural': 'Passport Details',
            },
        ),
        migrations.CreateModel(
            name='CombinedRequestTransportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_order', models.PositiveIntegerField(default=1)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('passengers', models.IntegerField(default=1)),
                ('vehicle_type_preference', models.CharField(blank=True, help_text='sedan, suv, van, bus, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('segment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_segments', to='combined_request.combinedrequest')),
            ],
            options={
                'verbose_name': 'Transport Segment',
                'verbose_name_plural': 'Transport Segments',
                'ordering': ['segment_order', 'pickup_date', 'pickup_time'],
            },
        ),
    ]
