# Generated by Django 5.0.2 on 2026-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combined_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedrequest",
            name="accommodation_gender",
            field=models.CharField(
                blank=True,
                help_text="Requestor gender for room allocation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="transport_purpose",
            field=models.TextField(
                blank=True, help_text="Purpose / reason for transport", null=True
            ),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="transport_tsr_reference",
            field=models.CharField(
                blank=True,
                help_text="Related TSR reference number",
                max_length=100,
                null=True,
            ),
        ),
    ]
