# Generated by Django 5.0.2 on 2026-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combined_request", "0002_add_transport_purpose_tsr_ref_accommodation_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedrequest",
            name="accommodation_flight_arrival_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="accommodation_flight_departure_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="accommodation_room_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="accommodation_special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="advance_bank_account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="advance_bank_account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="advance_bank_branch_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="advance_bank_currency",
            field=models.CharField(blank=True, default="TMT", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="advance_bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="external_cost_center",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="external_full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="external_organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="external_ref_to_authority_letter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="trip_type",
            field=models.CharField(
                blank=True,
                default="Round Trip",
                help_text="One Way / Round Trip",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_additional_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_application_fees_borne_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_approximately_arrival_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_citizenship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_contact_telephone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_cost_centre_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_current_employer_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_current_employer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_duration_of_stay",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_education_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_entry_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_family_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_itinerary_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_marital_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_passport_date_of_issuance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_passport_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_passport_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_passport_place_of_issuance",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_place_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_request_type",
            field=models.CharField(
                blank=True, default="VISA", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_supporting_documents_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_travel_purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_trf_reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_trip_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_trip_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequest",
            name="visa_work_visit_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequesttransportsegment",
            name="day_of_week",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="combinedrequesttransportsegment",
            name="transport_type",
            field=models.CharField(
                blank=True, help_text="car, van, bus, etc.", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="combinedrequest",
            name="accommodation_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional accommodation data (overflow)",
            ),
        ),
        migrations.AlterField(
            model_name="combinedrequest",
            name="travel_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores meal_selections list and advance_amount_items list",
            ),
        ),
        migrations.AlterField(
            model_name="combinedrequest",
            name="visa_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional visa data overflow"
            ),
        ),
        migrations.AlterField(
            model_name="combinedrequesttransportsegment",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="combinedrequesttransportsegment",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
