# Generated by Django 5.2.16 on 2026-08-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("combined_request", "0004_remove_combinedrequest_estimated_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combinedrequesttransportsegment",
            name="transport_type",
        ),
    ]
