# Generated by Django 5.0.2 on 2025-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_role', models.CharField(max_length=255)),
                ('step_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Not Started', max_length=255)),
                ('step_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expenseapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='expenseapproval',
            name='expense',
        ),
    ]
