# Generated by Django 5.0.2 on 2025-10-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_claimsapprovalstep_remove_expenseapproval_approver_and_more'),
        ('trf', '0002_travelrequest_remove_travelrequestform_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='trf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='trf.travelrequest'),
        ),
        migrations.AddField(
            model_name='claimsapprovalstep',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseclaim'),
        ),
        migrations.DeleteModel(
            name='ExpenseApproval',
        ),
    ]
