# Generated by Django 5.0.2 on 2025-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenseclaim_trf_claimsapprovalstep_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
