# Generated by Django 5.0.2 on 2025-11-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_add_request_number_to_expenseclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='cheque_receipt_no',
            field=models.CharField(blank=True, help_text='Payment reference or cheque number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='payment_method',
            field=models.CharField(blank=True, help_text='BANK_TRANSFER, CHEQUE, or CASH', max_length=20, null=True),
        ),
    ]
