# Generated by Django 5.0.2 on 2025-10-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_flightbooking_trf_alter_hotelbooking_trf'),
        ('trf', '0002_travelrequest_remove_travelrequestform_requester_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelRequestForm',
        ),
        migrations.AlterUniqueTogether(
            name='trfdailymealselection',
            unique_together={('trf', 'meal_date')},
        ),
    ]
