# Generated by Django 5.0.2 on 2025-10-25 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0003_delete_travelrequestform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(default='Draft', help_text='Dynamic status set by workflow engine', max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
