# Generated by Django 5.0.2 on 2025-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0004_update_status_field_for_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='request_number',
            field=models.CharField(blank=True, help_text='Auto-generated request number (e.g., TSR-20250702-1423-NYC-PCYX)', max_length=50, null=True, unique=True),
        ),
    ]
