# Generated by Django 5.0.2 on 2025-11-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0005_travelrequest_request_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfcompanytransportdetail',
            name='trf',
        ),
        migrations.DeleteModel(
            name='TrfAccommodationDetail',
        ),
        migrations.DeleteModel(
            name='TrfCompanyTransportDetail',
        ),
    ]
