# Generated by Django 5.0.2 on 2026-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0006_remove_accommodation_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfpassportdetail',
            name='passport_file',
            field=models.FileField(blank=True, help_text='Uploaded passport scan/photo', null=True, upload_to='trf/passports/'),
        ),
    ]
