# Generated by Django 5.2.8 on 2026-02-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trf', '0007_add_passport_file_to_trfpassportdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfadvancebankdetail',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='trfadvancebankdetail',
            name='swift_code',
        ),
    ]
