# Generated by Django 5.0.2 on 2026-05-06 10:43

import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0008_remove_swift_iban_from_bank_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trfadvancebankdetail",
            name="account_name",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trfadvancebankdetail",
            name="account_number",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trfpassportdetail",
            name="passport_number",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
    ]
