# Generated by Django 5.2.16 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0010_encrypt_existing_sensitive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelrequest",
            name="meal_processing_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Arranged", "Arranged"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
