# Generated by Django 5.2.16 on 2026-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0011_add_meal_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelrequest",
            name="advance_consent_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Requestor acknowledged the advance amount refund/deduction Terms and Conditions (Overseas/Home Leave only).",
            ),
        ),
        migrations.AddField(
            model_name="travelrequest",
            name="advance_consent_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
