# Generated by Django 5.2.16 on 2026-08-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0012_add_advance_consent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrfFlightBooking",
        ),
    ]
