# Generated by Django 5.2.17 on 2026-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0013_delete_trfflightbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelrequest",
            name="department_focal_notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the Department Focal has already been notified that this request's travel arrangements are fully complete — prevents re-notifying on every subsequent save once notified.",
            ),
        ),
    ]
