# Generated by Django 5.2.17 on 2026-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0014_travelrequest_department_focal_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelrequest",
            name="advance_consent_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Requestor acknowledged the advance amount refund/deduction Terms and Conditions (Overseas only).",
            ),
        ),
    ]
