# Generated by Django 5.2.17 on 2026-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trf", "0015_alter_travelrequest_advance_consent_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="trfapprovalstep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
