# Generated by Django 5.2.1 on 2025-05-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('trip_count', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='TravelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_trip_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_opportunities', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_trend', models.ManyToManyField(related_name='analytics', to='insights.monthlytrend')),
                ('spend_by_category', models.ManyToManyField(related_name='analytics', to='insights.categoryspend')),
                ('top_destinations', models.ManyToManyField(related_name='analytics', to='insights.destinationstat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Travel Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('COST_SAVING', 'Cost Saving'), ('BOOKING_TIMING', 'Booking Timing'), ('PREFERRED_VENDOR', 'Preferred Vendor'), ('TRAVEL_PATTERN', 'Travel Pattern'), ('POLICY_COMPLIANCE', 'Policy Compliance')], default='COST_SAVING', max_length=20)),
                ('potential_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
