# Generated by Django 5.2.16 on 2026-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelanalytics",
            name="spend_by_category",
        ),
        migrations.RemoveField(
            model_name="travelanalytics",
            name="top_destinations",
        ),
        migrations.RemoveField(
            model_name="travelanalytics",
            name="monthly_trend",
        ),
        migrations.RemoveField(
            model_name="travelanalytics",
            name="user",
        ),
        migrations.RemoveField(
            model_name="travelinsight",
            name="user",
        ),
        migrations.DeleteModel(
            name="CategorySpend",
        ),
        migrations.DeleteModel(
            name="DestinationStat",
        ),
        migrations.DeleteModel(
            name="MonthlyTrend",
        ),
        migrations.DeleteModel(
            name="TravelAnalytics",
        ),
        migrations.DeleteModel(
            name="TravelInsight",
        ),
    ]
