"""Add user authentication fields

Revision ID: bd25d28785b3
Revises: 
Create Date: 2025-05-26 19:35:08.604182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd25d28785b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_requests', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('review_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('processing_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('rejection_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('travel_requests', sa.Column('authority_letter_no', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('hlp_number', sa.String(), nullable=True))
    op.add_column('travel_requests', sa.Column('travel_start_date', sa.DateTime(), nullable=True))
    op.add_column('travel_requests', sa.Column('travel_end_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('EMPLOYEE', 'FOCAL', 'HOD', 'TICKETING_CLERK', 'EXTERNAL', name='userrole'), server_default='EMPLOYEE', nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), server_default='General', nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('travel_requests', 'travel_end_date')
    op.drop_column('travel_requests', 'travel_start_date')
    op.drop_column('travel_requests', 'hlp_number')
    op.drop_column('travel_requests', 'organization')
    op.drop_column('travel_requests', 'authority_letter_no')
    op.drop_column('travel_requests', 'rejection_reason')
    op.drop_column('travel_requests', 'rejection_date')
    op.drop_column('travel_requests', 'processing_date')
    op.drop_column('travel_requests', 'approval_date')
    op.drop_column('travel_requests', 'review_date')
    op.drop_column('travel_requests', 'submission_date')
    # ### end Alembic commands ###
